site_name: Recipe Bank
site_author: Tatenda Tachivona
site_description: My own curated digital cookbook
site_url: https://itstachie.github.io/Recipe-Bank/
repo_url: https://github.com/ItsTachie/Recipe-Bank
repo_name: Recipe-Bank
edit_uri: ""


theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs

nav:
  - Home: index.md

  - Staples & Classics:
      - Sadza & Relishes: 
          - Overview: staples/sadza/Overview.md
          - Basic Sadza: staples/sadza/sadza.md
          - Sadza nemukaka: staples/sadza/nemukaka.md
          - Sadza nemaveggie nenyama: staples/sadza/nenyama.md
      - Pasta:
          - Overview: staples/pasta/Overview.md
          - Creamy Tuscan Pasta: staples/pasta/creamy_tuscan_pasta.md
          - Marinara Pasta: staples/pasta/marinara_pasta.md
          - Bolognese: staples/pasta/spaghetti_bolognese.md
          - Alfredo: staples/pasta/fettuccine_alfredo.md
          - Mushroom Alfredo: staples/pasta/mushroom_alfredo.md
          - Mac & Cheese: staples/pasta/mac_n_cheese.md
          - Carbonara: staples/pasta/carbonara.md
      - Rice:
          - Standalones:
              - Overview: staples/rice/Overview.md
              - Egg Fried Rice: staples/rice/egg_fried_rice.md
          - Chicken and Rice Galore: 
              - Overview: staples/rice/chicken_and_rice_master.md
              - Rice Components:
                  - Red Tomato Rice: staples/rice/modules/red_rice.md
                  - Turmeric Yellow Rice: staples/rice/modules/yellow_rice.md
                  - Garlic Butter Rice: staples/rice/modules/garlic_rice.md
              - Chicken Components:
                  - Honey Garlic Chicken: staples/rice/modules/honey_garlic.md
                  - Buffalo Chicken: staples/rice/modules/buffalo_chicken.md
                  - BBQ Glazed Chicken: staples/rice/modules/bbq_chicken.md
              - Side Components:
                  - Pico de Gallo: staples/rice/modules/pico.md
                  - Creamy Coleslaw: staples/rice/modules/coleslaw.md
                  - Classic Potato Salad: staples/rice/modules/potato_salad.md
      - Potatoes:
          - Overview: staples/potatoes/Overview.md
          
  - Curries & Stews:
      - Overview: stews/Overview.md
      - Butter Chicken: stews/butter_chicken.md

  - Global Flavors:
      - Chinese:
          - Overview: global/chinese/Overview.md
      - European:
          - Overview: global/european/Overview.md

          