site_name: Recipe Bank
site_author: Tatenda Tachivona
site_description: My own curated digital cookbook
site_url: https://itstachie.github.io/Recipe-Bank/
repo_url: https://github.com/ItsTachie/Recipe-Bank
repo_name: Recipe-Bank
edit_uri: ""


theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs

nav:
  - Home: index.md

  - Staples & Classics:
      - Sadza & Relishes: 
          - Overview: staples/sadza/Overview.md
          - Basic Sadza: staples/sadza/sadza.md
          - Sadza nemukaka: staples/sadza/nemukaka.md
          - Sadza nemaveggie nenyama: staples/sadza/nenyama.md
      - Pasta:
          - Overview: staples/pasta/Overview.md
          - Creamy Tuscan Pasta: staples/pasta/creamy_tuscan_pasta.md
          - Marinara Pasta: staples/pasta/marinara_pasta.md
          - Bolognese: staples/pasta/spaghetti_bolognese.md
          - Alfredo: staples/pasta/fettuccine_alfredo.md
          - Mushroom Alfredo: staples/pasta/mushroom_alfredo.md
      - Rice:
          - Overview: staples/rice/Overview.md
      - Potatoes:
          - Overview: staples/potatoes/Overview.md
          
  - Curries & Stews:
      - Overview: stews/Overview.md

  - Global Flavors:
      - Chinese:
          - Overview: global/chinese/Overview.md
      - Middle Eastern:
          - Overview: global/middle_eastern/Overview.md
      - European:
          - Overview: global/european/Overview.md

          